description: Logs from some python app
paths:
  - /opt/myapp/logs/pythonapp.log
groks:
  - "%{TIMESTAMP_ISO8601:log_timestamp} - %{}"
timestamp:
  find: "\\d+-\\d+-\\d+ (\\d+):(\\d+):(\\d+)"
  replace: "%Y-%m-%d %H:%M:%S"
###
2017-04-24 10:40:45,455 - pythonapp_ext.extensions - INFO - Executing3 at /opt/org/pythonapp/ai/temp/api-24042017-1267306868411149911.24-1392

2017-04-24 10:40:48,808 - pythonapp_ext.cli - ERROR - Exception while running extension2
Traceback (most recent call last):
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/cli.py", line 109, in extension
    extension_svc.run_exec(config, args, module)
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/extensions.py", line 97, in run_exec
    self._run(path, pid, module, False, True)
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/extensions.py", line 257, in _run
    context.upload_file_service.upload(instance.shared_file(), instance.filename(), instance.to_string())
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/extensions.py", line 465, in to_string
    content = self.content()
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/extensions.py", line 541, in content
    with open(self.template_path, 'r') as fs:
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/site-packages/pythonapp_ext/extensions.py", line 538, in template_path
    return os.path.join(self.template_dir, self.default_template_name)
  File "/opt/org/pythonapp/users/appuser/.conda/envs/pythonapp/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
